# Generated by Django 6.0.1 on 2026-02-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateTimeField()),
                ('priroty', models.CharField(choices=[('low', 'faible'), ('medium', 'moyen'), ('high', 'fort')], max_length=10)),
                ('notified', models.BooleanField(default=False)),
                ('event_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.event_list')),
            ],
        ),
    ]
